DietDiary/Controllers/EatenMealController.cs
using DietDiary.Models;
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DietDiary.Controllers
{
    [Authorize]
    public class EatenMealController : Controller
    {
        private IUnitOfWork Uow;
        public EatenMealController(IUnitOfWork uow)
        {
            Uow = uow;
        }

        public ActionResult CreateEatenMeal(int id)
        {
            var meal = Uow.MealsRepository.GetMeal(id);
            List<MealType> mealTypes = new List<MealType>();
            mealTypes = Uow.MealTypesRepository.GetMealTypes();
            EatenMealVM model = new EatenMealVM()
            {
                MealId = meal.MealId,
                MealName = meal.Name,
                MealTypeList = new SelectList(mealTypes, "Id", "Name")
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateEatenMeal(EatenMealVM model)
        {
            if (ModelState.IsValid)
            {
                var meal = Uow.MealsRepository.GetMeal(model.MealId);
                EatenMeal eatenMeal = new EatenMeal()
                {
                    Meal = meal,
                    Serving = model.Serving,
                    Username = User.Identity.Name,
                    MealType = Uow.MealTypesRepository.GetMealType(model.MealTypeID),
                    Date = model.Date
                };
                Uow.EatenMealsRepository.AddEatenMeal(eatenMeal);
                Uow.Commit();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                List<MealType> mealTypes = new List<MealType>();
                mealTypes = Uow.MealTypesRepository.GetMealTypes();
                model.MealTypeList = new SelectList(mealTypes, "Id", "Name");
                return View(model);
            }
        }

        public ActionResult Delete(int id)
        {
            Uow.EatenMealsRepository.Delete(id);
            Uow.Commit();
            return RedirectToAction("Index", "Home");
        }
    }
}

DietDiary/Controllers/MealController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Domain.Entities;

namespace DietDiary.Controllers
{
    [Authorize]
    public class MealController : Controller
    {
        private IUnitOfWork Uow;
        public MealController(IUnitOfWork uow)
        {
            Uow = uow;
        }

        public ActionResult List(int? page, string name = null)
        {
            int pageNumber = page ?? 1;
            var model =
                Uow.MealsRepository.GetMeals()
                .Where(r => name == null || r.Name.StartsWith(name, StringComparison.OrdinalIgnoreCase))
                .Select(r => new Meal
                {
                    MealId = r.MealId,
                    Name = r.Name,
                    Protein = r.Protein,
                    Carbohydrates = r.Carbohydrates,
                    Fat = r.Fat,
                    Calories = r.Calories
                }).ToPagedList(pageNumber, 50);

            var et = Uow.EatenMealsRepository.GetEatenMeals(User.Identity.Name, null);
            List<Meal> meals = new List<Meal>();
            foreach (var item in et)
            {
                meals.Add(item.Meal);
            }
            meals.Reverse();
            meals = meals.GroupBy(o => o.MealId).Select(o => o.FirstOrDefault()).ToList();
            ViewBag.LastAddedEatenMeal = meals.Take(10);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_Meals", model);
            }
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Meal model)
        {
            if (ModelState.IsValid)
            {
                Uow.MealsRepository.SaveMeal(model);
                Uow.Commit();
                TempData["message"] = string.Format("Dodano do bazy produkt o nazwie {0}", model.Name);
                return RedirectToAction("List");
            }

            else
            {
                return View(model);
            }

        }

        public ViewResult Edit(int id)
        {
            var model = Uow.MealsRepository.GetMeals().Where(x => x.MealId.Equals(id)).SingleOrDefault();
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Meal model)
        {
            if (ModelState.IsValid)
            {
                Uow.MealsRepository.SaveMeal(model);
                Uow.Commit();
                TempData["message"] = string.Format("Edycja produktu o nazwie {0} zakończona powodzeniem.", model.Name);
                return RedirectToAction("List");
            }

            else
            {
                return View(model);
            }
        }

    }
}

DietDiary/Views/Meal/Create.cshtml
@model Domain.Entities.Meal

@{
    ViewBag.Title = "Create";
}

<h2>Dodawanie nowego posiłku <small>(wartości w 100 gramach produktu)</small></h2>
@using (Html.BeginForm("Create", "Meal", FormMethod.Post, new { @class = "form" }))
{
    <div class="form-group">
        @Html.Label("Nazwa")
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div class="form-group">
        @Html.Label("Białko (g)")
        @Html.TextBoxFor(x => x.Protein, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Protein)
    </div>
    <div class="form-group">
        @Html.Label("Węglowodany (g)")
        @Html.TextBoxFor(x => x.Carbohydrates, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Carbohydrates)
    </div>
    <div class="form-group">
        @Html.Label("Tłuszcze (g)")
        @Html.TextBoxFor(x => x.Fat, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Fat)
    </div>
    <div class="form-group">
        @Html.Label("Kalorie (kcal)")
        @Html.TextBoxFor(x => x.Calories, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Calories)
    </div>
    <button type="submit" class="btn btn-info">Zapisz</button>
    @Html.ActionLink("Anuluj i wróć do listy", "List");
}

DietDiary/Views/Meal/Edit.cshtml
@model Domain.Entities.Meal

@{
    ViewBag.Title = "Edycja";
}

<h2>Edycja produktu <small>(wartości w 100 gramach produktu)</small></h2>
@using (Html.BeginForm("Edit", "Meal", FormMethod.Post, new { @class = "form" }))
{
    @Html.HiddenFor(x => x.MealId)
    <div class="form-group">
        @Html.Label("Nazwa")
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div class="form-group">
        @Html.Label("Białko (g)")
        @Html.TextBoxFor(x => x.Protein, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Protein)
    </div>
    <div class="form-group">
        @Html.Label("Węglowodany (g)")
        @Html.TextBoxFor(x => x.Carbohydrates, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Carbohydrates)
    </div>
    <div class="form-group">
        @Html.Label("Tłuszcze (g)")
        @Html.TextBoxFor(x => x.Fat, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Fat)
    </div>
    <div class="form-group">
        @Html.Label("Kalorie (kcal)")
        @Html.TextBoxFor(x => x.Calories, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Calories)
    </div>
    <button type="submit" class="btn btn-info">Zapisz</button>
    @Html.ActionLink("Anuluj i wróć do listy", "List");
}

DietDiary/Views/Meal/List.cshtml
@model IPagedList<Domain.Entities.Meal>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["message"] != null)
{
    <div class="alert alert-success">@TempData["message"]</div>
}

<div class="col-md-12">
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                        Ostatnie dodane posiłki do dziennika
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table table-striped table-hover ">
                        <thead>
                            <tr>
                                <th>Nazwa</th>
                                <th style="text-align: center">Białko (g)</th>
                                <th style="text-align: center">Węglowodany (g)</th>
                                <th style="text-align: center">Tłuszcze (g)</th>
                                <th style="text-align: center">Kalorie (kcal)</th>
                                <th style="text-align: center">Dodaj do dziennika</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var meal in ViewBag.LastAddedEatenMeal)
                            {
                                <tr>
                                    <td>@meal.Name</td>
                                    <td style="text-align: center">@meal.Protein</td>
                                    <td style="text-align: center">@meal.Carbohydrates</td>
                                    <td style="text-align: center">@meal.Fat</td>
                                    <td style="text-align: center">@meal.Calories</td>
                                    <td style="text-align: center"><a href="@Url.Action("CreateEatenMeal", "EatenMeal", new { @id = @meal.MealId })">Dodaj</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-md-6 col-md-offset-4">
    <form method="get" action="@Url.Action("List")" class="form-inline">
        <input type="search" class="form-control" id="searchInput">
        <button type="submit" class="btn btn-info" id="searchButton">Szukaj po nazwie</button>
    </form>
</div>

@Html.Partial("_Meals", Model)